name: CD Pipeline to LocalStack (staging and production)
on:
  push:
    branches:
      - staging
  workflow_dispatch: {}
  release:
    types: published

env:
  PORT: 5001
  IMAGE: ${{vars.IMAGE}}:${{github.sha}}
jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup, test, and build project
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test

  build:
    needs: test
    runs-on: ubuntu-latest
    name: Build Docker image and deploy to LocalStack
    env:
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: us-east-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate for Docker Hub
        id: docker-auth
        env:
          D_USER: ${{secrets.DOCKER_USER}}
          D_PASS: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $D_USER --password-stdin

      - name: Build and tag Image
        run: |
          docker build -t ${{env.IMAGE}} .

      - name: Push the image to Docker hub
        run: |
          docker push ${{env.IMAGE}}

      - name: Start LocalStack
        run: |
          docker run -d -p 4566:4566 -p 4571:4571 localstack/localstack

      - name: Deploy to LocalStack - Production environment (If a new release was published from the main branch)
        if: github.event_name == 'release' && github.event.action == 'published' && github.event.release.target_commitish == 'main'
        run: |
          echo "Deploying to LocalStack Production"
          awslocal ecs create-cluster --cluster-name myapp-prod
          awslocal ecs register-task-definition \
            --family myapp-prod \
            --network-mode bridge \
            --container-definitions '[{"name":"myapp","image":"${{env.IMAGE}}","memory":512,"cpu":256,"essential":true,"portMappings":[{"containerPort":5001,"hostPort":5001}]}]'
          awslocal ecs create-service \
            --cluster myapp-prod \
            --service-name myapp-service-prod \
            --task-definition myapp-prod \
            --desired-count 1

      - name: Deploy to LocalStack - Staging environment
        if: github.ref != 'refs/heads/main'
        run: |
          echo "Deploying to LocalStack Staging"
          awslocal ecs create-cluster --cluster-name myapp-staging
          awslocal ecs register-task-definition \
            --family myapp-staging \
            --network-mode bridge \
            --container-definitions '[{"name":"myapp","image":"${{env.IMAGE}}","memory":512,"cpu":256,"essential":true,"portMappings":[{"containerPort":5001,"hostPort":5001}]}]'
          awslocal ecs create-service \
            --cluster myapp-staging \
            --service-name myapp-service-staging \
            --task-definition myapp-staging \
            --desired-count 1
